### Communication others values
MSR_BEGIN_BYTE = b'\x1b'
MSR_ENDING_FIELD = b'\x3f\x1c'
MSR_DATA_BEGIN_CODE = b'\x1b\x73'

### Commands
MSR_RESET = b'\x1b\x61'
MSR_FIRMWARE_VERSION = b'\x1b\x76'
MSR_DEVICE_MODEL = b'\x1b\x74'
MSR_COMMUNICATION_TEST = b'\x1b\x65'
MSR_RAM_TEST = b'\x1b\x87'
MSR_SENSOR_TEST = b'\x1b\x86'
MSR_COERCIVITY_STATUS = b'\x1b\x64'
MSR_SET_HIGH_COERCIVITY = b'\x1b\x78'
MSR_SET_LOW_COERCIVITY = b'\x1b\x79'
MSR_SET_BPC = b'\x1b\x6f'
MSR_SET_BPI = b'\x1b\x62'
MSR_ALL_LED_ON = b'\x1b\x82'
MSR_GREEN_LED_ON = b'\x1b\x83'
MSR_YELLOW_LED_ON = b'\x1b\x84'
MSR_RED_LED_ON = b'\x1b\x85'
MSR_ERASE_TRACKS = b'\x1b\x63'
MSR_WRITE_ISO = b'\x1b\x77'
###

### Response
MSR_COMMUNICATION_TEST_EXPECTED_RESPONSE = b'\x79'
MSR_RAM_TEST_SUCCESS = b'\x30'
MSR_RAM_TEST_FAIL = b'\x41'
MSR_SENSOR_TEST_SUCCESS = b'\x30'
MSR_COERCIVITY_STATUS_HIGH = b'h'
MSR_COERCIVITY_STATUS_LOW = b'l'
MSR_SET_COERCIVITY_SUCCESS = b'\x30'
MSR_SET_BPC_SUCCESS = b'\x30'
MSR_ERASE_SUCCESS = b'\x30'
MSR_ERASE_FAIL = b'\x41'
MSR_SET_BPI_SUCCESS = b'\x30'
MSR_SET_BPI_FAIL = b'\x41'
MSR_WRITE_ISO_SUCCESS = b'\x30'
###

### Other values
MSR_BPC_MIN_VALUE = 5
MSR_BPC_MAX_VALUE = 8

MSR_BPI_75 = 75
MSR_BPI_210 = 210

MSR_BPI_HEX_CODE = { 1: {75: b'\xa1', 210: b'\xa0'}, 2: {75: b'\x4b', 210: b'\xd2'}, 3: {75: b'\xc0', 210: b'\xc1'}}